name: RPG
version: 1.0.0
main: org.example.code.rpg.RPG
api-version: '1.20'
load: STARTUP
commands:
  광부:
    description: 광부 n차 전직 책을 받습니다.
    usage: /광부 <1~4차>

  돈:
    description: 현재 잔액을 확인합니다.
    usage: /돈

  도움말:
    description: MinerSurvival 플러그인의 도움말을 확인합니다.
    usage: /도움말

  메뉴:
    description: 다양한 기능이 있는 메뉴를 오픈합니다.
    usage: /메뉴

  이름변경권:
    description: 이름 변경권을 받습니다.
    usage: /이름변경권